version: '3.8'
name: anaconda_mongo
services:
  anaconda:
    image: continuumio/anaconda3
    container_name: anaconda
    volumes:
      - ./:/opt/notebooks
    ports:
      - "8888:8888"
    command:
      /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    tty: true
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    hostname: server
    container_name: anaconda_server
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo_db_data:/data/db
      - mongo_db_config:/data/configdb
      - ./:/app

volumes:
  mongo_db_data:
    external: true
  mongo_db_config:
    external: true